export const contactsList = [
  {
    name: "Morpheus",
    surname: "Barbados",
    age: 35,
    gender: "man",
    phone: "234567987",
    email: "m.barbadosg@vfybnko.cos",
    department: "front-end",
    photo: "Cont-1.png",
  },
  {
    name: "Helen",
    surname: "Carstovaso",
    age: 45,
    gender: "man",
    phone: "344558976",
    email: "h.cartovasg@vfybnko.cos",
    department: "back-end",
    photo: "Cont-9.png",
  },
  {
    name: "Peteros",
    surname: "Ivanivsky",
    age: 35,
    gender: "man",
    phone: "345679876",
    email: "p.ivanivsky@vfybnko.cos",
    department: "front-end",
    photo: "Cont-4.png",
  },
  {
    name: "Marije",
    surname: "Nitrovska",
    age: 25,
    gender: "woman",
    phone: "344559876",
    email: "m.nitrovskag@vfybnko.cos",
    department: "back-end",
    photo: "Cont-3.png",
  },
  {
    name: "Neo",
    surname: "Hospodsky",
    age: 27,
    gender: "woman",
    phone: "23456776",
    email: "n.hospodskyg@vfybnko.cos",
    department: "front-end",
    photo: "Cont-11.png",
  },
  {
    name: "Triniti",
    surname: "Petrovskaja",
    age: 18,
    gender: "woman",
    phone: "3445589876",
    email: "t.petrovskaj@vfybnko.cos",
    department: "back-end",
    photo: "Cont-6.png",
  },
  {
    name: "Yodo",
    surname: "Lionevsky",
    age: 35,
    gender: "man",
    phone: "345679876",
    email: "y.linoveskg@vfybnko.cos",
    department: "front-end",
    photo: "Cont-12.png",
  },
  {
    name: "Boris",
    surname: "Welowitor",
    age: 65,
    gender: "man",
    phone: "2345679876",
    email: "b.welowitorg@vfybnko.cos",
    department: "front-end",
    photo: "Cont-7.png",
  },
  {
    name: "Signus",
    surname: "Heliocentr",
    age: 31,
    gender: "man",
    phone: "235679877",
    email: "s.heliocentr@vfybnko.cos",
    department: "front-end",
    photo: "Cont-2.png",
  },
  {
    name: "Petropol",
    surname: "Neptunov",
    age: 23,
    gender: "man",
    phone: "235665497",
    email: "n.petroasg@vfybnko.cos",
    department: "front-end",
    photo: "Cont-10.png",
  },
  {
    name: "Werusta",
    surname: "Matriksova",
    age: 19,
    gender: "woman",
    phone: "3445589876",
    email: "w.matriksov@vfybnko.cos",
    department: "back-end",
    photo: "Cont-8.png",
  },
  {
    name: "Agent",
    surname: "Smitt",
    age: 41,
    gender: "man",
    phone: "2345679876",
    email: "a.smitt@vfybnko.cos",
    department: "front-end",
    photo: "Cont-5.png",
  },
];
